config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :articles do
      resources :comments
    end
  end

  resources :articles do
    resources :likes
  end

  resources :relationships,       only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "edit", to: "users#edit", as: "edit"
  get "signup", to: "users#user_new", as: "signup"
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  get 'forgot_passwords', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
# layout 'for_login'
  def show

    @user = User.find_by(token: params[:id])
    if (params[:token])
      @token = @user.token
      render layout: 'for_login'
    end

    if @user
      @token = @user.token
      render layout: 'for_login'
    else
      flash[:alert] = "*Your reset password link has expired."
      redirect_to forgot_passwords_path unless @user
    end

    # render :show ,layout: 'for_login'
  end

  def create

     @user = User.find_by(token: params[:token])
     if (params[:token])
     @token = @user.token
     end
     # render layout: 'for_login'
     # render layout: 'for_login'
    if @user && @user.update(password: params[:password],password_confirmation: params[:password_confirmation], token: nil)
      flash[:alert] = "*Your password has been changed. Please sign in."
      redirect_to login_path
      else
    # if @user
    #   @token = @user.token
    #   render 'show' ,layout: 'for_login'
    flash[:alert] = "*Something Went Wrong. Password min length is 3 and Please make sure Password Confirmation Matches."
    redirect_to password_reset_path(@token)
    # else
    #   # redirect_to expired_token_path
    #   flash[:alert] = "Your reset password link has expired."
    #    redirect_to forgot_passwords_path
    # end
    end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/expired_token.html.erb
<h2>Your reset password link has expired.</h2>

app/views/password_resets/show.html.erb
<body  class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default"  >
<!-- begin:: Page -->
<div class="m-grid m-grid--hor m-grid--root m-page">
  <div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--signin m-login--2 m-login-2--skin-1" id="m_login" style="background-image: url(/assets/app/media/img//bg/bg-7.jpg);">
    <div class="m-grid__item m-grid__item--fluid m-login__wrapper">
      <div class="m-login__container">
        <div class="m-login__signin">
          <div class="m-login__logo">
            <a href="#">
              <img src="/assets/app/media/img//logos/logo-1.png">
            </a>
          </div>
          <div class="m-login__head">
            <div class="form-group m-form__group">

            <h3 class="m-login__title">
              Reset Your Password.
            </h3>
            <div class="m-login__desc">
              Enter your new password:
            </div>
          </div>

          </div>
          <%=form_tag password_resets_path, class:"m-login__form m-form" , local: true do |form| %>

<!--            <div class="form-group m-form__group">-->
              <%# if @user.errors.any? %>
<!--                <div id="error_explanation">-->


                  <%# @user.errors.full_messages.each do |msg| %>

<!--                    <p class = "text text-danger">*&nbsp<%#= msg %></p>-->

                  <%# end %>

<!--                </div>-->
              <%# end %>
<!--            </div>-->

            <div class="form-group m-form__group">
              <span class = "text text-danger" id=”alert”><%= alert %></span>
            </div>
            <form class="m-login__form m-form" action="">
              <div class="form-group m-form__group">
                <input class="form-control m-input" type="password" placeholder="Password" name="password" id="m_email" >
              </div>
              <div class="form-group m-form__group">
                <input class="form-control m-input" type="password" placeholder="Confirm Password" name="password_confirmation" id="m_email" >
              </div>
              <%=hidden_field_tag :token, @token %>
              <div class="m-login__form-action">
                <%= submit_tag 'Request', class: 'btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn m-login__btn--primary' %>
                <!--              <button id="m_login_forget_password_submit" class="btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn m-login__btn--primary" name="commit">-->
                <!--                Request-->
                <!--              </button>-->
                &nbsp;&nbsp;
                <a href="<%=root_url %>" class="btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn">
                  Cancel
                </a>
              </div>
            </form>
          <%end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end:: Page -->
<!--begin::Base Scripts -->
<script src="assets/vendors/base/vendors.bundle.js" type="text/javascript"></script>
<script src="assets/demo/default/base/scripts.bundle.js" type="text/javascript"></script>
<!--begin::Page Snippets -->
<script src="assets/snippets/custom/pages/user/login.js" type="text/javascript"></script>
<!--end::Page Snippets -->
</body>
<!-- end::Body -->