config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :articles do
      resources :comments
    end
  end

  resources :articles do
    resources :likes
  end

  resources :relationships,       only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "edit", to: "users#edit", as: "edit"
  get "signup", to: "users#user_new", as: "signup"
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  get 'forgot_passwords', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  # validate :image_size_validation
  # validate :validate_minimum_image_size
  # include CarrierWave::Validations::ActiveModel
  # mount_uploader :image, ImageUploader
  # validate :image_type
  has_one_attached :image

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title,
            length: { minimum: 5 }
  validates :text, presence: true,
            length: { minimum: 10 }


  validates :image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg'],
            dimension: { width: { min: 720, max: 1920 },
                         height: { min: 520, max: 1080 }, message: 'is not given between dimension. Please Provide image with dimensions between [720-1920]x[550-1080]' }
  has_many :taggings
  has_many :tags, through: :taggings

def self.search(search)
  #debugger
if search
  Article.where("lower(title) LIKE ?","%#{search.downcase}%")
#   # debugger
#   # if article
#   #   article
  else
    Article.all
  end
# else
#   Article.all
#
# end
end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  # private
  #
  # def image_type
  #   if image.attached? == false
  #     errors.add(:image, "is missing!")
  #   end
  #   if !image.content_type.in?(%('image/jpeg image/png'))
  #     errors.add(:image, "needs to be a jpeg or png!")
  #   end
  #
  # end

  # private
  #
  # def image_size_validation
  #   errors[:image] << "should be less than 5MB" if image.size > 5.megabytes
  # end

  # def validate_minimum_image_size
  #   # image = MiniMagick::Image.open(image.path)
  #
  #     errors[:image] << "should be greater than or equal to 720x550"  if image.width < 720 && image.height < 550
  #
  #   end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
# layout "articles_index" ,only: [ :index]
layout "create_article", only: [:new, :update, :edit, :create]

  def index
    # @articles = Article.search(params[:search])

    @articles  = Article.paginate(:page => params[:page], :per_page=>6)
    # @articles = Article.all

    render layout: 'articles_index'
    # if params[:search]
    #   @articles =   Article.where("lower(:title) LIKE :title",title: "%#{:search.downcase}%")
    # else
    #   @articles = Article.all
    # end

    #@articles = Article.all
    #@user = User.find(params[:user_id])
    #@article = @user.articles.find(params[:id])
  end

  def show
    #@user = User.find(params[:user_id])
    #@article = @user.articles.find(params[:id])

    @article = Article.find(params[:id])
    render layout: 'show_article'
  end

  def new
    @article = Article.new
  end

  def edit
    #@user = User.find(params[:user_id])
    #@article = @user.articles.find(params[:id])
     @article = Article.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.create(article_params)
    #redirect_to user_article_path(@user)
    #@article = Article.new(article_params)

    if @article.save
      redirect_to user_article_path(@user,@article)
    else
      render 'new', layout: 'create_article'
    end
  end

  def update
    @user = User.find(params[:user_id])
    #@article = @user.articles.find(params[:id])
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to user_article_path(@user,@article)
    else
      render 'edit', layout: 'create_article'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    #@article = @user.articles.find(params[:id])
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to user_articles_path(@user)
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :search, :image, :all_tags)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end
end

app/views/articles/_create_article.html.erb
<!--   header section-->
<section id="section-services" class="section pad-bot30 bg-white">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <a href="<%=root_path %>">
          <h1>My Blog</h1></a>
        <h6><span class="label label-info">Logged in as <%= current_user.email %> </span></h6>
        <!--          <img class="navbar-logo" src="img/logo.png" alt="Vector Logo" style="width: 35%">-->
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-8">
            <!--              <a class="btn btn-default" href="Logged in as admin@gamil.com"> Logged in as admin@gamil.com </a>-->
            <a class="btn btn-default" href="<%=new_user_article_path(current_user) %>"> + Create Article</a>
            <a class="btn btn-default" href="<%=root_path %>"> Home</a>
            <a class="btn btn-default" href="<%=user_path(current_user) %>"> Profile </a>
            <% if current_user.role == "admin" %>
              <a class="btn btn-default" href="<%=users_path %>"> Admin Panel </a>
            <%end %>
            <a class="btn btn-default" href="<%=logout_path %>"> Log Out </a>
          </div>
          <!--            Search Begin-->
          <div class="col-md-4">
            <%= form_tag(root_url, method: :get, html: {class: 'form-search'}) do %>
              <form class="form-search">

                <div class="form-group">
                  <%= text_field_tag :search, params[:search],class: 'form-control', placeholder: 'Search Articles', value: '' %>
                  <%#= submit_tag name: nil,class: 'btn btn-primary' %>
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i>
                  </button>

                </div>
              </form>
            <%end %>
          </div>
          <!--            Search End-->
        </div>
      </div>
      <!--        <div class="col-md-12">-->
      <!--          <a href="create_article.html" class="btn btn-success">+ Create Article</a>-->
      <!--        </div>-->
    </div>
  </div>
</section>

<!-- section works -->
<section id="section-works" class="section appear clearfix">
  <div class="container">

    <div class="row">
      <div class="col-lg-12">
<!--        <div class="page-header">-->
          <h3>Create Article Here</h3>
<!--        </div>-->
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= form_with scope: :article, url: user_articles_path,id: 'create_article' ,local: true do |form| %>

          <div class="form-group">

            <% if @article.errors.any? %>
              <div id="error_explanation">

                <% @article.errors.full_messages.each do |msg| %>
                  <p class = "text text-danger">*&nbsp<%= msg %></p>
                <% end %>

              </div>
            <%end %>
          </div>

          <%= form.label :title %>
        <div class="form-group">
          <%= form.text_field :title, class: 'form-control', id: "title",  placeholder: "Enter your title here", required: true %>

          <!--          <input type="text" class="form-control" id="title" name="article[title]" placeholder="Enter your title here" required="">-->
        </div>
          <%= form.label 'Tags' %>
          <div class="form-group">
          <%= form.text_field :all_tags,class: 'form-control', placeholder: "Tags separated with comma" %>
          </div>

        <div class="row">
          <div class="col-lg-12">
            <label>Content</label>
          </div>
        </div>

        <div id="content-row">
          <div class="form-group">
            <%= form.text_area :text, id: "code_preview0",class: 'form-control', style: "height: 300px;" %>

            <!--            <textarea class="form-control" id="code_preview0" name="article[text]" style="height: 300px;"></textarea>-->
          </div>
        </div>

          <%= form.label 'Cover Photo' %><p>
        <%= form.file_field :image, onchange: 'validateFiles(this);',data: { max_file_size: 5.megabytes }, required: true %>
      </p>

          <p>
            <%= form.submit 'Submit', class: "btn btn-success" %>
            <%= link_to 'Cancel',user_articles_path, class: 'btn btn-danger' %>
          </p>

      </div>
<%end %>
    </div>
  </div>
</section>

<!--<script type="text/javascript">-->
<!--    $(document).ready(function () {-->
<!--        $("#create_article").validate();-->
<!--    });-->
<!--</script>-->

app/views/articles/_form.html.erb
<%= form_with scope: :article, url: user_articles_path, html: { multipart: true }, local: true do |form| %>
  <div class="form-group">

  <% if @article.errors.any? %>
    <div id="error_explanation">

        <% @article.errors.full_messages.each do |msg| %>
        <p class = "text text-danger">*&nbsp<%= msg %></p>
        <% end %>
    </div>
  <% end %>


    <%= form.label :title %><p>
    <%= form.text_field :title, class: 'form-control' %>
  </p>



    <%= form.label :text %><p>
    <%= form.text_area :text, class: 'form-control' %>
  </p>

    <%= form.label :image %><p>
    <%= form.file_field :image, onchange: 'validateFiles(this);',data: { max_file_size: 5.megabytes } ,required: true %>
  </p>

  <p>
    <%= form.submit 'Submit', class: "btn btn-success btn-xs" %>
    <%= link_to 'Cancel',user_articles_path, class: 'btn btn-danger btn-xs' %>
  </p>

  </div>
<% end %>

app/views/articles/_indexnew.html.erb
<%if current_user %>

<!--  <section id="section-services" class="section pad-bot30 bg-white">-->
<!--    <div class="container">-->
<!--      <div class="row">-->
<!--        <div class="col-md-6">-->
<!--          <h1>My Blog</h1>-->
<!--          <h5><span class="label label-info">Logged in as <%#= current_user.email %> </span></h5>-->
          <!--<img class="navbar-logo" src="img/logo.png" alt="Vector Logo">-->


<!--        </div>-->

<!--      <div class="col-md-6">-->
<!--        <div class="row">-->
          <%#= form_tag(user_articles_path, method: :get, html: {class: 'form-search'}) do %>
<!--          <form class="form-search">-->

<!--            <div class="col-md-6"></div>-->
<!--            <div class="col-md-6">-->


<!--              <div class="form-group">-->
                <%#= text_field_tag :search, params[:search],class: 'form-control', placeholder: 'Search Articles', value: '' %>
               <%#= submit_tag 'Search', name: nil,class: 'btn btn-primary' %>
<!--                <button type="submit" class="btn btn-primary" data-disable-with="Go">-->
<!--                  Go-->
<!--                </button>-->

<!--            </div>-->
<!--            </div>-->
<!--          </form>-->
          <%# end %>
<!--        </div>-->
<!--      </div>-->
<!--      </div>-->
<!--      <div>-->
<!--        <span class="label label-primary"> Logged in as <%#= current_user.email %></span>-->

        <%#= link_to 'Home', root_url ,class: 'btn btn-success btn-xs'%>
        <%# if current_user.role == "admin" %>
          <%#= link_to 'Admin Panel', users_path, class: 'btn btn-danger btn-xs' %>
        <%#end %>
        <%#= link_to 'Profile',current_user,class: 'btn btn-info btn-xs'%>

        <%#= link_to 'Log Out', logout_path, class: 'btn btn-danger btn-xs' %>
<!--        <br><br>-->

        <%#= link_to new_user_article_path(current_user) ,class: 'btn btn-success btn-lg' do%>
<!--        <i class="glyphicon glyphicon-plus"></i> Create Article-->
        <%#end %>

<!--      </div>-->



<!--    </div>-->
<!--  </section>-->

  <!--   header section-->
  <section id="section-services" class="section pad-bot30 bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <a href="<%=root_path %>">
          <h1>My Blog</h1></a>
          <h6><span class="label label-info">Logged in as <%= current_user.email %> </span></h6>
          <!--          <img class="navbar-logo" src="img/logo.png" alt="Vector Logo" style="width: 35%">-->
        </div>
        <div class="col-md-10">
          <div class="row">
            <div class="col-md-8">
              <!--              <a class="btn btn-default" href="Logged in as admin@gamil.com"> Logged in as admin@gamil.com </a>-->
              <a class="btn btn-default" href="<%=new_user_article_path(current_user) %>"> + Create Article</a>
              <a class="btn btn-default" href="<%=root_path %>"> Home</a>
              <a class="btn btn-default" href="<%=user_path(current_user) %>"> Profile </a>
              <% if current_user.role == "admin" %>
                <a class="btn btn-default" href="<%=users_path %>"> Admin Panel </a>
              <%end %>
              <a class="btn btn-default" href="<%=logout_path %>"> Log Out </a>
            </div>
            <!--            Search Begin-->
            <div class="col-md-4">
              <%= form_tag(root_url, method: :get, html: {class: 'form-search'}) do %>
                <form class="form-search">

                  <div class="form-group">
                    <%= text_field_tag :search, params[:search],class: 'form-control', placeholder: 'Search Articles', value: '' %>
                    <%#= submit_tag name: nil,class: 'btn btn-primary' %>
                    <button type="submit" class="btn btn-primary">
                      <i class="fa fa-search"></i>
                    </button>

                  </div>
                </form>
              <%end %>
            </div>
            <!--            Search End-->
          </div>
        </div>
        <!--        <div class="col-md-12">-->
        <!--          <a href="create_article.html" class="btn btn-success">+ Create Article</a>-->
        <!--        </div>-->
      </div>
    </div>
  </section>

  <section id="section-works" class="section appear clearfix">
    <div class="container">
      <% @user = User.find(params[:user_id])%>
      <% @articles  = @user.articles.paginate(:page => params[:page], :per_page=>6)%>
      <% if @user.articles.search(params[:search]).count == 0  %>
        <h2 class="text-danger">No Article Found</h2>
        <%=link_to 'Return to My Articles',  user_articles_path, class: 'btn btn-info' %>
      <%else %>
      <%end %>
      <%= will_paginate @articles %>
      <div class="row">

        <div class="col-md-12">
          <div class="row">

            <div class="portfolio-items isotopeWrapper clearfix" id="3">


              <%#articles = Article.search(params[:search]) %>

              <% @user.articles.paginate(:page => params[:page], :per_page=>6).search(params[:search]).each do |article| %>

              <article class="col-md-4">
                <div class="imgBlock">
                  <div class="img-container">
                    <%# if article.image.attached? %>

                      <%#= image_tag article.image.variant(combine_options: { resize: "720x550^", extent: "720x550^", auto_orient: true, gravity: "center"}).processed, alt: 'Image', class: 'img-responsive '%>
                      <%#else %>
                      <%= image_tag("portfolio/img1.jpg") %>
                      <%#end %>
                  <div class="img-overlay">
                    <p class="img-btn">
                      <span class="date"><%= article.updated_at.strftime("%b %d, %Y") %></span>
                      <%if article.likes.count == 0 %>
                        <%else %>
                      <span>|</span>
                      <span class="url-text"><%= article.likes.count %> <%= (article.likes.count) == 1 ? 'Like' : 'Likes'%></span>
                        <%end %>
                      <% if article.user == @user || current_user.role == "admin" %>
                        <span>|</span>
                      <%= link_to 'Edit', edit_user_article_path(@user,article), class: "url-text"%>
                        <span>|</span>
                      <%= link_to 'Delete', [article.user, article],
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' }, class: 'url-text' %>
                      <%end %>
                    <h2 class="h2-text">
                      <a href="<%= user_article_path(@user,article)%>"><%=truncate(article.title, length: 65) %></a>
                    </h2>
                    </p>
                  </div>
                </div>
                </div>
              </article>
              <%end %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>

  <%end %>

app/views/articles/_show_article.html.erb
<!--   header section-->
<section id="section-services" class="section pad-bot30 bg-white">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <a href="<%=root_path %>">
          <h1>My Blog</h1></a>
        <h6><span class="label label-info">Logged in as <%= current_user.email %> </span></h6>
        <!--          <img class="navbar-logo" src="img/logo.png" alt="Vector Logo" style="width: 35%">-->
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-8">
            <!--              <a class="btn btn-default" href="Logged in as admin@gamil.com"> Logged in as admin@gamil.com </a>-->
            <a class="btn btn-default" href="<%=new_user_article_path(current_user) %>"> + Create Article</a>
            <a class="btn btn-default" href="<%=root_path %>"> Home</a>
            <a class="btn btn-default" href="<%=user_path(current_user) %>"> Profile </a>
            <% if current_user.role == "admin" %>
              <a class="btn btn-default" href="<%=users_path %>"> Admin Panel </a>
            <%end %>
            <a class="btn btn-default" href="<%=logout_path %>"> Log Out </a>
          </div>
          <!--            Search Begin-->
          <div class="col-md-4">
            <%= form_tag(root_url, method: :get, html: {class: 'form-search'}) do %>
              <form class="form-search">

                <div class="form-group">
                  <%= text_field_tag :search, params[:search],class: 'form-control', placeholder: 'Search Articles', value: '' %>
                  <%#= submit_tag name: nil,class: 'btn btn-primary' %>
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i>
                  </button>

                </div>
              </form>
            <%end %>
          </div>
          <!--            Search End-->
        </div>
      </div>
      <!--        <div class="col-md-12">-->
      <!--          <a href="create_article.html" class="btn btn-success">+ Create Article</a>-->
      <!--        </div>-->
    </div>
  </div>
</section>

<!-- section works -->
<section id="section-works" class="section appear clearfix">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <h1><%= @article.title %> </h1>
      </div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-1">
<!--            <img src="/img/user.jpg" alt="User image" class="user_image">-->
            <%# if @article.user.avatar.attached? %>
              <%#= image_tag @article.user.avatar, alt: "User image", class: "user_image"%>
            <%#else %>
              <img src="/img/user.jpg" alt="User image" class="user_image">
            <%#end %>
          </div>
          <div class="col-md-2">

              <%=@article.user.name %><span>&nbsp&nbsp</span>
              <%@user = User.find(params[:user_id]) %>
              <% if @article.user == current_user || current_user.role == "admin" %>
                <a class="btn btn-default btn-follow btn-xs" href="<%=edit_user_article_path(@article.user_id, @article) %>"> Edit Article </a>
                <%#= link_to 'Edit Article', edit_user_article_path(@article.user_id, @article),class: 'btn btn-warning btn-xs'%>
              <%else %>

<!--                <a class="btn btn-default btn-follow btn-xs" data-method="post" href="<%#=relationship_path(@user) %>"> Follow </a>-->
            <% pre_follow = current_user.active_relationships.find_by(followed_id: @article.user_id) %>
            <% if !pre_follow %>
                  <%= form_for(current_user.active_relationships.build, local: true) do |f| %>
                    <%= hidden_field_tag :followed_id, @article.user.id %>
                    <%= f.submit "Follow", class: "btn btn-default btn-follow btn-xs" %>
                <%end %>
                <%else %>
                  <%= form_for(current_user.active_relationships.find_by(followed_id: @article.user_id), html: { method: :delete }, local: true) do |f| %>
                    <%= f.submit "Unfollow", class: "btn btn-default btn-follow btn-xs" %>
                    <%end %>
                <%end %>
                <%end %>





                <%# if !current_user.following?(@article.user_id) %>
                    <%#= form_for(current_user.active_relationships.build, remote: true) do |f| %>
<!--                      <div><%#= hidden_field_tag :followed_id, @article.user.id %></div>-->
                      <%#= f.submit "Follow", class: "btn btn-default btn-follow" %>
                    <%# end %>

                    <%#end %>
                    <%#end %>




            <p>Last update:<span>&nbsp</span> <%= @article.updated_at.strftime("%b %d, %Y") %></p>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <br>
        <%# if @article.image.attached? %>
          <%#= image_tag @article.image, alt: 'Back Ground image', class: 'bc-image'%>
        <%#else %>
          <%#= image_tag("portfolio/img1.jpg", alt: 'Back Ground image', class: 'bc-image') %>
          <img src="/img/bg-4.jpg" alt="Back Ground image" class="bc-image">
        <%#end %>
<!--        <img src="/img/bg-4.jpg" alt="Back Ground image" class="bc-image">-->
      </div>
      <div class="col-md-12">
        <p class="blog-para">

          <%= sanitize @article.text, tags: %w(strong em a b font br p table tbody tr td ol li u img iframe span blockquote pre h1 h2 h3 h4 h5 h6 div strike hr),
                       attributes: %w(href face class src style ta rget frameborder width height color) %>

        </p>
        <br>
      </div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-10">
<!--            <a class="btn btn-default btn-follow" href="#"> Follow </a>-->
<!--            <a class="btn btn-default btn-follow" href="#"> Follow </a>-->
<!--            <a class="btn btn-default btn-follow" href="#"> Follow </a>-->
<!--            <a class="btn btn-default btn-follow" href="#"> Follow </a>-->
<!--            <a class="btn btn-default btn-follow" href="#"> Follow </a>-->
           Tags:&nbsp <%=raw tag_links(@article.all_tags)%>
          </div>
          <div class="col-md-2">
            <% pre_like = @article.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
              <a class="btn btn-primary btn-like" data-method="delete" href="<%=article_like_path(@article, pre_like) %>"> Unlike </a>
              <%#= link_to 'Unlike', article_like_path(@article, pre_like), method: :delete, class: 'btn btn-danger btn-xs' %>
            <% else %>
              <a class="btn btn-primary btn-like" data-method="post" href="<%=article_likes_path(@article) %>"> Like </a>
              <%#= link_to 'Like', article_likes_path(@article), method: :post,class: 'btn btn-success btn-xs'  %>
            <% end %>
<!--            <a class="btn btn-primary btn-like" href="#"> Like </a>-->
            <span style="margin-left: 20%"><%= @article.likes.count %></span>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <hr class="blog-hr">
      </div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-2">
<!--            <img src="/img/user.jpg" alt="User image" class="user_image">-->
            <%# if @article.user.avatar.attached? %>
              <%#= image_tag @article.user.avatar, alt: "User image", class: "user_image"%>
            <%#else %>
              <img src="/img/user.jpg" alt="User image" class="user_image">
            <%#end %>
          </div>
          <div class="col-md-8">
            <h4>Written by</h4>
            <h2><%=@article.user.name %></h2>
<!--            <p>-->
<!--              Writes about relationships and pop psychology for The New York Times, Vice, and more. Author of “Clearly, I Didn’t Think This Through.” Lives in Philly.-->
<!--            </p>-->
          </div>
<!--          <div id="follow_form">-->
            <div class="col-md-2">
            <%# if current_user.following?(@article.user_id) %>
<!--              <a class="btn btn-default btn-follow" href="#"> Follow </a>-->


              <!--                <a class="btn btn-default btn-follow btn-xs" data-method="post" href="<%#=relationship_path(@user) %>"> Follow </a>-->
              <% if @article.user == current_user %>
                <%else %>
                <% pre_follow = current_user.active_relationships.find_by(followed_id: @article.user_id) %>
                <% if !pre_follow %>
                  <%= form_for(current_user.active_relationships.build, local: true) do |f| %>
                    <%= hidden_field_tag :followed_id, @article.user.id %>
                    <%= f.submit "Follow", class: "btn btn-default btn-follow" %>
                  <%end %>
                <%else %>
                  <%= form_for(current_user.active_relationships.find_by(followed_id: @article.user_id), html: { method: :delete }, local: true) do |f| %>
                    <%= f.submit "Unfollow", class: "btn btn-default btn-follow" %>
                  <%end %>
                <%end %>
                <%end %>


                <%#= form_for(current_user.active_relationships.build, remote: true) do |f| %>
<!--                  <div><%#= hidden_field_tag :followed_id, @user.id %></div>-->
                  <%#= f.submit "Follow", class: "btn btn-default btn-follow" %>
                <%# end %>
            <%# else %>
<!--              <a class="btn btn-default btn-follow" href="#"> Unfollow </a>-->

                <%#= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
                  <%#= f.submit "Unfollow", class: "btn btn-default btn-follow" %>
                <%# end %>
            <%# end %>
<!--          </div>-->
          </div>
<!--          <div class="col-md-2">-->
<!--            <a class="btn btn-default btn-follow" href="#"> Follow </a>-->
<!--          </div>-->
        </div>
      </div>
      <div class="col-md-12">
        <hr class="blog-hr">
      </div>
      <div class="col-md-12 comment-section">
        <h2>Comments</h2>
        <div class="row">
          <% @article.comments.each do |comment| %>
            <% @user= comment.user%>
            <%# @user = User.find(params[id]) %>
          <div class="col-md-12">

            <div class="row">
              <br>
              <div class="col-md-1">

                <%#debugger %>
<!--                <img src="/img/user.jpg" alt="User image" class="comment_image">-->
                <%# if @user.avatar.attached? %>
                  <%#= image_tag @user.avatar, alt: "User image", class: "comment_image"%>
                <%#else %>
                  <img src="/img/user.jpg" alt="User image" class="comment_image">
                <%#end %>
              </div>
              <div class="col-md-8">
                <p>
                 <strong> <%= comment.commenter %></strong>
                </p>

                <p>
                 <%= comment.body %>
                </p>

                <p>
                  <% if comment.user == current_user || current_user.role == "admin"  %>
                    <%= link_to 'Remove', [@article.user,comment.article, comment],
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %>
                  <%end %>
                </p>

              </div>
            </div>
          </div>
            <%end %>
          <%= form_with(model: [ current_user,@article, @article.comments.build ], local: true) do |form| %>
          <div class="col-md-12">

            <form>
              <br>
              <p>
                <%= form.text_field :commenter, value: current_user.name, class: 'hide' %></p>

              <p>
                <%= form.text_area :body, class:'form-control col-md-12'%><br></p>
              <p>

                <%= form.submit 'Submit', class: 'btn btn-success btn-sm', style: 'margin-top: 2%; float: left;' %>
              </p>
<!--              <textarea class="form-control col-md-12"></textarea>-->
<!--              <button class="btn btn-success" style="margin-top: 2%; float: right;">Submit</button>-->
            </form>
          </div>
        </div>
            <%end %>
      </div>
    </div>
  </div>
</section>

<!--<script type="text/javascript">-->
<!--    $(document).ready(function() {-->
<!--        $('#code_preview0').summernote({height: 200});-->
<!--    });-->
<!--</script>-->

app/views/articles/index.html.erb
<%=render 'indexnew' %>