config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :articles do
      resources :comments
    end
  end

  resources :articles do
    resources :likes
  end

  resources :relationships,       only: [:create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  get '/:token/confirm_email/', :to => "users#confirm_email", as: 'confirm_email'
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "edit", to: "users#edit", as: "edit"
  get "signup", to: "users#user_new", as: "signup"
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  get 'forgot_passwords', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'password_resets#expired_token'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  #before_create :confirmation_token
  has_secure_password
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
           foreign_key: "follower_id",
           dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship",
           foreign_key: "followed_id",
           dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  has_one_attached :avatar
  validates :avatar, content_type: ['image/png', 'image/jpg', 'image/jpeg'],
            dimension: { width: { min: 300, max: 1920 },
                         height: { min: 300, max: 1080 }, message: 'is not given between dimension. Please Provide image with dimensions between [300-1920]x[300-1080]' }


  validates :name, presence: true, format: { with: /\A[a-zA-Z\s]+\z/i, message: "can only be letters." }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  validates_confirmation_of :password, confirmation: { case_sensitive: true }
  validates_length_of :password, minimum: 3
  validates_uniqueness_of :email , except: [:edit]

  def self.search(search)
    #debugger
    if search
      User.where("lower(name) LIKE ?","%#{search.downcase}%")
#   # debugger
#   # if article
#   #   article
    else
      User.all
    end
    # else
    #   Article.all
    #
    # end
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil

  end

  def set_confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

  def update_with_token!
    update_column(:token, generate_token)
  end

  # private

  def generate_token
    SecureRandom.urlsafe_base64
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   #layout "for_login", except: [:index, :confirm_email, :destroy, :show]
   #layout "users_index"
  def index

    @user = User.all
    render layout: 'users_index'

  end

  def user_new
  #render layout: "for_login"
    @user = User.new
    if current_user
    if current_user.role == 'admin'
       render layout: 'users_index'
      else
    end
    else
       render layout: "for_login"
    end
  end

  def edit
    @user = User.find(params[:id])
    render layout: 'articles_index'
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.set_confirmation_token
      @user.save(:validate => false)
      UserMailer.registration_confirmation(@user).deliver_now
      flash[:alert] = "Please confirm your email address to continue"
      if current_user
        if current_user.role == 'admin'
          redirect_to users_path
          else
        end
        else
      redirect_to root_url
      end
    else
      if current_user
        if current_user.role == 'admin'
          render 'user_new', layout: 'users_index'
        else
        end
      else
        render 'user_new', layout: 'for_login'
      end



    end
    end


  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit', layout: 'articles_index'
    end
  end

  def show
    @user = User.find(params[:id])
    render layout: 'articles_index'
  end

  def destroy

    @user = User.find(params[:id])

    @user.destroy

    redirect_to users_path
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:token])
    if user
      user.email_confirmed = true
      user.confirm_token = nil
      user.save(:validate => false)
      #flash[:alert] = "Welcome to the Sample App! Your email has been confirmed.
      #Please sign in to continue."
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
      #redirect_to login_path
    else
      flash[:alert] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end



  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :search, :avatar, :role)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<section id="section-services" class="section pad-bot30 bg-white">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <a href="<%=root_path %>">
          <h1>My Blog</h1></a>
        <h6><span class="label label-info">Logged in as <%= current_user.email %> </span></h6>
        <!--          <img class="navbar-logo" src="img/logo.png" alt="Vector Logo" style="width: 35%">-->
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-8">
            <!--              <a class="btn btn-default" href="Logged in as admin@gamil.com"> Logged in as admin@gamil.com </a>-->
            <a class="btn btn-default" href="<%=new_user_article_path(current_user) %>"> + Create Article</a>
            <!--              <a class="btn btn-default" href="<%#=edit_user_path(@user) %>"> Edit Profile </a>-->
            <a class="btn btn-default" href="<%=root_path %>"> Home</a>
            <a class="btn btn-default" href="<%=user_articles_path(@user) %>"> My Articles</a>
            <% if current_user.role == "admin" %>
              <a class="btn btn-default" href="<%=users_path %>"> Admin Panel </a>
            <%end %>
            <a class="btn btn-default" href="<%=logout_path %>"> Log Out </a>
          </div>
          <!--            Search Begin-->
          <div class="col-md-4">
            <%= form_tag(root_url, method: :get, html: {class: 'form-search'}) do %>
              <form class="form-search">

                <div class="form-group">
                  <%= text_field_tag :search, params[:search],class: 'form-control', placeholder: 'Search Articles', value: '' %>
                  <%#= submit_tag name: nil,class: 'btn btn-primary' %>
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i>
                  </button>

                </div>
              </form>
            <%end %>
          </div>
          <!--            Search End-->
        </div>
      </div>
      <!--        <div class="col-md-12">-->
      <!--          <a href="create_article.html" class="btn btn-success">+ Create Article</a>-->
      <!--        </div>-->
    </div>
  </div>
</section>


<section id="section-works" class="section appear clearfix">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

<%= form_with model: @user, local: true do |form| %>


<% if @user.errors.any? %>
  <div id="error_explanation">

<p>
      <% @user.errors.full_messages.each do |msg| %>
      <p class = "text text-danger">*&nbsp<%= msg %></p>
      <% end %>

  </div>

<% end %>
    </p>

      <label for="username">Name</label>
    <p>
  <%= form.text_field :name %></p>

      <label for="emailaddress">Email Address</label>
  <p>
  <%= form.text_field :email,:disabled => true %></p>

    <label for="password">Password</label>
    <p>
      <%= form.password_field :password %></p>

    <label for="Password">Confirm Password</label>
    <p>
      <%= form.password_field :password_confirmation %></p>
 <%if current_user.role == 'admin' %>
          <label for="Password">User Type</label>
          <p>
            <%= form.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %></p>
            <%end %>

    <%= form.label 'Profile Photo' %><p>
  <%= form.file_field :avatar, onchange: 'validateFiles(this);',data: { max_file_size: 5.megabytes } %>
</p>

<p>
  <%= form.submit 'Update', class: "btn btn-success " %>
    <%= link_to 'Cancel',user_path, class: 'btn btn-danger' %>

</p>


<% end %>
  </div>
    </div>
</div>

</section>

app/views/users/_old_index.html.erb
<% if current_user %>
  <div class="container">

    <% if current_user.role == "admin" %>
      <div class="page-header">
        <h1>Users</h1>
      </div>
      <span class="label label-primary"> Logged in as <%= current_user.email %></span>
      <%= link_to 'Log Out', logout_path, class: 'btn btn-danger btn-xs' %>
      <%= link_to 'Profile', current_user, class: 'btn btn-info btn-xs' %>
      <%= link_to 'Articles', user_articles_path(current_user), class: 'btn btn-primary btn-xs' %>
      <p>
        <br>
        <%= link_to 'Add New User', new_user_path, class: 'btn btn-success text-uppercase' %>
      </p>
      <table class="table table-striped">
        <thead>
        <tr>
          <br>
          <th>Name</th>
          <th>Email</th>
          <th>Token-Status</th>
          <th>Token</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @user.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.email_confirmed %></td>
            <td><%= user.confirm_token %></td>
            <td><%= link_to 'Show', user_path(user), class: 'label label-info' %></td>
            <td><%= link_to 'Edit', edit_user_path(user), class: 'label label-success'%></td>
            <td><%= link_to 'Destroy', user_path(user),
                            method: :delete,
                            data: { confirm: 'Are you sure?' }, class: 'label label-danger' %></td>
          </tr>
        <% end %>
        </tbody>
      </table><br>
      </div>
    <%else %>
      <div class="container">
        <div class="text-center">
          <h1><span class="label label-danger">
    ONLY ADMIN CAN VIEW THIS</span></h1></div></div>
    <%end %>


<%end %>

app/views/users/_signup3.html.erb
<%= form_with model: @user, local: true do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">

        <div class="wrapper-page">

          <div class="m-t-40 card-box">
            <div class="text-center">
              <h2 class="text-uppercase m-t-0 m-b-30">
                <a href="<%=root_url %>" class="text-success">
                                    <span>
                                        <h1> My Blog</h1>
                                      <!--<img src="assets/images/logo_dark.png" alt="" height="30">-->
                                    </span>
                </a>
              </h2>
              <!--<h4 class="text-uppercase font-bold m-b-0">Sign In</h4>-->
            </div>
            <div class="account-content">
              <div class="form-group m-b-20">
                <div class="col-xs-12">
                  <p id=”alert”><%= alert %></p>
                </div></div>


              <div class="form-group m-b-20">
                <div class="col-xs-12">
                  <% if @user.errors.any? %>
                    <div id="error_explanation">

                      <ul>
                        <% @user.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                </div>
              </div>

              <form class="form-horizontal" action="#">

                <div class="form-group m-b-20">
                  <div class="col-xs-12">

                    <label for="username">Name</label>
                    <input class="form-control" type="text" name="user[name]" required="" placeholder="Ghayyur Ali">
                  </div>
                </div>

                <div class="form-group m-b-20">
                  <div class="col-xs-12">
                    <br>
                    <label for="emailaddress">Email address</label>
                    <input class="form-control" type="email" name="user[email]" required="" placeholder="ghayyur9@gmail.com">
                  </div>
                </div>

                <div class="form-group m-b-20">
                  <div class="col-xs-12">
                    <br>
                    <label for="password">Password</label>
                    <input class="form-control" type="password" name="user[password]" required="" placeholder="Enter your password">
                  </div>
                </div>

                <div class="form-group m-b-20">
                  <div class="col-xs-12">
                    <br>
                    <label for="password">Confirm Password</label>
                    <input class="form-control" type="password" name="user[password_confirmation]" required=""  placeholder="Confirm your password">
                  </div>
                </div>

                <div class="form-group account-btn text-center m-t-10">
                  <div class="col-xs-12">
                    <br>
                    <button class="btn btn-lg btn-primary btn-block" type="submit" name="commit" value="Sign Up Free" data-disable-with="Sign Up Free">Sign Up Free</button>
                  </div>
                </div>

              </form>
<%end %>

<div class="clearfix"></div>

</div>
</div>
<!-- end card-box-->


<div class="row m-t-50">
  <div class="col-sm-12 text-center">
    <p class="text-muted">Already have an account?  <%= link_to 'Sign in', root_url%></p>
  </div>
</div>

</div>
<!-- end wrapper -->

</div>
</div>
</div>

app/views/users/_signup4.html.erb
<div class="m-grid m-grid--hor m-grid--root m-page">
  <div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--signin m-login--2 m-login-2--skin-1" id="m_login" style="background-image: url(assets/app/media/img//bg/bg-7.jpg);">
    <div class="m-grid__item m-grid__item--fluid m-login__wrapper">
      <div class="m-login__container">
        <div class="m-login__signin">
          <div class="m-login__logo">
            <a href="<%=root_url %>">
              <img src="assets/app/media/img//logos/logo-1.png">
            </a>
          </div>
          <div class="m-login__head">
            <h3 class="m-login__title">
              Sign Up
            </h3>
            <div class="m-login__desc">
              Enter your details to create your account:
            </div>
          </div>
          <%= form_with model: @user, class: 'm-login__form m-form', local: true do |form| %>
          <form class="m-login__form m-form" action="">
            <div class="form-group m-form__group">
              <% if @user.errors.any? %>
                <div id="error_explanation">


                  <% @user.errors.full_messages.each do |msg| %>

                    <p class = "text text-danger">*&nbsp<%= msg %></p>

                  <% end %>

                </div>
              <% end %>
            </div>

            <div class="form-group m-form__group">
              <%=form.text_field :name, class: 'form-control m-input',placeholder:"Full Name", required: '' %>
<!--              <input class="form-control m-input" type="text" placeholder="Fullname" name="user[name]" required="">-->
            </div>
            <div class="form-group m-form__group">
              <%=form.text_field :email, class: 'form-control m-input',placeholder:"Email", required: '' %>
<!--              <input class="form-control m-input" type="text" placeholder="Email" name="user[email]" required="">-->
            </div>
            <div class="form-group m-form__group">
              <%=form.password_field :password, class: 'form-control m-input',placeholder:"Password", required: '' %>
<!--              <input class="form-control m-input" type="password" placeholder="Password" name="user[password]" required="">-->
            </div>
            <div class="form-group m-form__group">
              <%=form.password_field :password_confirmation, class: 'form-control m-input',placeholder:"Confirm Password", required: '' %>
<!--              <input class="form-control m-input m-login__form-input--last" type="password" placeholder="Confirm Password" name="user[password_confirmation]" required="">-->
            </div>
            <div class="form-group m-form__group">
              <div class="m-login__form-action">
<!--              <div class="m-login__form-action">-->
<!--              <br>&nbsp&nbsp-->

              <%=form.file_field :avatar, onchange: 'validateFiles(this);',data: { max_file_size: 5.megabytes },class: "btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn m-login__btn--primary" ,required: true %>
              <!--              <input class="form-control m-input" type="text" placeholder="Email" name="user[email]" required="">-->
              </div>
            </div>

<!--            </div>-->
            <!--<div class="row form-group m-form__group m-login__form-sub">-->
            <!--<div class="col m&#45;&#45;align-left">-->
            <!--<label class="m-checkbox m-checkbox&#45;&#45;light">-->
            <!--<input type="checkbox" name="agree">-->
            <!--I Agree the-->
            <!--<a href="#" class="m-link m-link&#45;&#45;focus">-->
            <!--terms and conditions-->
            <!--</a>-->
            <!--.-->
            <!--<span></span>-->
            <!--</label>-->
            <!--<span class="m-form__help"></span>-->
            <!--</div>-->
            <!--</div>-->
            <div class="m-login__form-action">
              <%= form.submit 'Submit',class: "btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn m-login__btn--primary" %>
<!--              <button type="submit" name="commit" value="Sign Up Free" data-disable-with="Sign Up Free" class="btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn m-login__btn--primary">-->
<!--                Sign Up-->
<!--              </button>-->
              &nbsp;&nbsp;
              <a href="<%=root_url %>" class="btn m-btn m-btn--pill m-btn--custom m-btn--air m-login__btn">
                Cancel
              </a>
            </div>
          </form>
            <%end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_signup_old.html.erb
<%= form_with model: @user, local: true do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">

        <div class="wrapper-page">

          <div class="m-t-40 card-box">
            <div class="text-center">
              <h2 class="text-uppercase m-t-0 m-b-30">
                <a href="<%=root_url %>" class="text-success">
                                    <span>
                                        <h1> My Blog</h1>
                                      <!--<img src="assets/images/logo_dark.png" alt="" height="30">-->
                                    </span>
                </a>
              </h2>
              <!--<h4 class="text-uppercase font-bold m-b-0">Sign In</h4>-->
            </div>
            <div class="account-content">
              <div class="form-group m-b-20">
                <div class="col-xs-12">
                  <p class = "text text-danger" id=”alert”><%= alert %></p></div></div>



              <div class="form-group m-b-20">
                <div class="col-xs-12">
                  <% if @user.errors.any? %>
                    <div id="error_explanation">


                      <% @user.errors.full_messages.each do |msg| %>

                        <p class = "text text-danger">*&nbsp<%= msg %></p>

                      <% end %>

                    </div>
                  <% end %>
                </div>
              </div>

              <form class="form-horizontal" action="#">

                <div class="form-group m-b-20">
                  <div class="col-xs-12">

                    <label for="username">Name</label>
                    <input class="form-control" type="text" name="user[name]" required="" placeholder="Ghayyur Ali" >
                  </div>
                </div>

                <div class="form-group m-b-20">
                  <div class="col-xs-12">
                    <br>
                    <label for="emailaddress">Email address</label>
                    <input class="form-control" type="email" name="user[email]" required="" placeholder="ghayyur9@gmail.com">
                  </div>
                </div>

                <div class="form-group m-b-20">
                  <div class="col-xs-12">
                    <br>
                    <label for="password">Password</label>
                    <input class="form-control" type="password" name="user[password]" required="" placeholder="Enter your password">
                  </div>
                </div>

                <div class="form-group m-b-20">
                  <div class="col-xs-12">
                    <br>
                    <label for="password">Confirm Password</label>
                    <input class="form-control" type="password" name="user[password_confirmation]" required=""  placeholder="Confirm your password">
                  </div>
                </div>

                <div class="form-group account-btn text-center m-t-10">
                  <div class="col-xs-12">
                    <br>
                    <button class="btn btn-lg btn-primary btn-block" type="submit" name="commit" value="Sign Up Free" data-disable-with="Sign Up Free">Sign Up Free</button>
                  </div>
                </div>

              </form>
<%end %>

<div class="clearfix"></div>

</div>
</div>
<!-- end card-box-->


<div class="row m-t-50">
  <div class="col-sm-12 text-center">
    <p class="text-muted">Already have an account?  <%= link_to 'Sign in', root_url%></p>
  </div>
</div>

</div>
<!-- end wrapper -->

</div>
</div>
</div>

app/views/users/edit.html.erb
<%if current_user %>
  <%=javascript_include_tag 'image.change' %>

<%= render 'form' %>

<%end %>

app/views/users/index.html.erb
<% if current_user %>
  <% if current_user.role == 'admin' %>
    <%= render 'new_index' %>
<%else %>
  <div class="container">
    <div class="text-center">
      <h1><span class="label label-danger">
    ONLY ADMIN CAN VIEW THIS</span></h1></div></div>
  <%end %>

<%end %>

app/views/users/show.html.erb
<%if current_user %>
<!--  <div class="container">-->
<!--    <div class="page-header">-->
<!--<h1>Details</h1>-->
<!--    </div>-->
<%# if current_user %>
<!--  <span class="label label-primary"> Logged in as <%#= current_user.email %></span>-->
  <%#= link_to 'Log Out', logout_path, class: 'btn btn-danger btn-xs' %>
<%# else %>
<%#end %>
<!--    </div>-->
<!--    <br>-->
<!--    <div class="container">-->
<!--<p>-->
<!--  <strong>Name:</strong>-->
  <%#= @user.name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Email:</strong>-->
  <%#= @user.email %>
<!--</p>-->

  <%#= link_to 'My Articles', user_articles_path(@user), class: 'btn btn-primary btn-xs' %>
<%#= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-danger btn-xs'%>

<!--    </div>-->

  <section id="section-services" class="section pad-bot30 bg-white">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <a href="<%=root_path %>">
            <h1>My Blog</h1></a>
          <h6><span class="label label-info">Logged in as <%= current_user.email %> </span></h6>
          <!--          <img class="navbar-logo" src="img/logo.png" alt="Vector Logo" style="width: 35%">-->
        </div>
        <div class="col-md-10">
          <div class="row">
            <div class="col-md-8">
              <!--              <a class="btn btn-default" href="Logged in as admin@gamil.com"> Logged in as admin@gamil.com </a>-->
              <a class="btn btn-default" href="<%=new_user_article_path(current_user) %>"> + Create Article</a>
<!--              <a class="btn btn-default" href="<%#=edit_user_path(@user) %>"> Edit Profile </a>-->
              <a class="btn btn-default" href="<%=root_path %>"> Home</a>
              <a class="btn btn-default" href="<%=user_articles_path(@user) %>"> My Articles</a>
              <% if current_user.role == "admin" %>
                <a class="btn btn-default" href="<%=users_path %>"> Admin Panel </a>
              <%end %>
              <a class="btn btn-default" href="<%=logout_path %>"> Log Out </a>
            </div>
            <!--            Search Begin-->
            <div class="col-md-4">
              <%= form_tag(root_url, method: :get, html: {class: 'form-search'}) do %>
                <form class="form-search">

                  <div class="form-group">
                    <%= text_field_tag :search, params[:search],class: 'form-control', placeholder: 'Search Articles', value: '' %>
                    <%#= submit_tag name: nil,class: 'btn btn-primary' %>
                    <button type="submit" class="btn btn-primary">
                      <i class="fa fa-search"></i>
                    </button>

                  </div>
                </form>
              <%end %>
            </div>
            <!--            Search End-->
          </div>
        </div>
        <!--        <div class="col-md-12">-->
        <!--          <a href="create_article.html" class="btn btn-success">+ Create Article</a>-->
        <!--        </div>-->
      </div>
    </div>
  </section>

  <section id="section-works" class="section appear clearfix">

<!--  <div class="col-md-12">-->
<!--    <hr class="blog-hr">-->
<!--  </div>-->
    <div class="container">
      <div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-2">
        <%# if @user.avatar.attached? %>
        <%#= image_tag @user.avatar, alt: "User image", class: "user_image"%>
          <%#else %>
          <img src="/img/user.jpg" alt="User image" class="user_image">
        <%#end %>
      </div>
      <div class="col-md-8"><br>
        <h4>Name: <strong><%=@user.name %></strong></h4>
        <h4>Email: <strong><%=@user.email %></strong></h4>
        <h4>Followers: <strong><%=@user.followers.count %></strong></h4>
        <h4>Following: <strong><%=@user.following.count %></strong></h4>

        <!--            <p>-->
        <!--              Writes about relationships and pop psychology for The New York Times, Vice, and more. Author of “Clearly, I Didn’t Think This Through.” Lives in Philly.-->
        <!--            </p>-->
      </div>
      <div class="col-md-2">
        <a class="btn btn-default btn-follow" href="<%=edit_user_path(@user) %>">Edit</a>
      </div>
    </div>
  </div>


<%end %>
</div>
</div>
</section>

app/views/users/user_new.html.erb
<% if current_user %>
<% if current_user.role == 'admin' %>
  <%=render 'admin_signup' %>
    <% else %>
  <%end %>
  <%else %>
<%= render 'signup4' %>

<%end %>